export const STORY_PROMPTS: string[] = [
  "A dragon who is afraid of fire",
  "The talking cat who became mayor",
  "A pirate ship that sails through clouds",
  "The tiny robot who wanted a pet",
  "A magical library where books come alive",
  "The bear who opened a bakery",
  "A girl who can talk to the moon",
  "The secret door in the old tree",
  "A penguin's adventure in the desert",
  "The boy who found a baby dragon",
  "A spaceship powered by laughter",
  "The fox and the magical paintbrush",
  "A mermaid who dreams of mountains",
  "The clock that could stop time",
  "A dog who delivers the mail",
  "The garden that grows candy",
  "A superhero whose power is kindness",
  "The owl who taught at a school",
  "A castle made entirely of ice cream",
  "The mouse who became an explorer",
  "A train that travels between worlds",
  "The cloud that wanted to be a mountain",
  "A squirrel's treasure map adventure",
  "The shoes that could dance on their own",
  "A friendly monster under the bed",
  "The rainbow that lost its colors",
  "A wizard's first day at school",
  "The bicycle that could fly",
  "A lost star trying to find its way home",
  "The elephant who learned to whisper",
  "A village inside a snow globe",
  "The caterpillar's big dream",
  "A chef who cooks with magic spices",
  "The lighthouse keeper's secret",
  "A bunny detective solves a mystery",
  "The music box that plays wishes",
  "A tree that tells bedtime stories",
  "The paper airplane that flew to space",
  "A jellyfish who loves to dance",
  "The little witch's potion goes wrong",
  "A toy soldier's midnight adventure",
  "The bridge between two magical kingdoms",
  "A bird who collects lost things",
  "The umbrella that controls the weather",
  "A turtle racing against the wind",
  "The invisible friend who became real",
  "A kingdom where kids make the rules",
  "The sunflower that could walk",
  "A detective cat in a haunted house",
  "The lantern that lights up dreams",
];
