-- 084_operational_policies_and_welcome_grant.sql
-- Store operational decisions as versioned, auditable policies and replace the
-- recurring free allowance with a one-time welcome grant.

CREATE TABLE IF NOT EXISTS public.operational_policies (
  policy_key text PRIMARY KEY CHECK (policy_key ~ '^[a-z][a-z0-9_]*$'),
  name text NOT NULL CHECK (char_length(btrim(name)) > 0),
  category text NOT NULL CHECK (category ~ '^[a-z][a-z0-9_]*$'),
  description text NOT NULL DEFAULT '',
  enabled boolean NOT NULL DEFAULT false,
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config_json) = 'object'),
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.operational_policy_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_key text NOT NULL REFERENCES public.operational_policies(policy_key) ON DELETE RESTRICT,
  policy_version integer NOT NULL CHECK (policy_version > 0),
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action_type text NOT NULL CHECK (action_type IN ('policy_created', 'policy_updated')),
  reason text NOT NULL CHECK (char_length(btrim(reason)) >= 4),
  before_json jsonb,
  after_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_operational_policy_audit_lookup
  ON public.operational_policy_audit_events (policy_key, created_at DESC, id DESC);

ALTER TABLE public.operational_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_policy_audit_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.operational_policies FROM anon, authenticated;
REVOKE ALL ON TABLE public.operational_policy_audit_events FROM anon, authenticated;
GRANT ALL ON TABLE public.operational_policies TO service_role;
GRANT ALL ON TABLE public.operational_policy_audit_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.operational_policy_audit_events_id_seq TO service_role;

INSERT INTO public.operational_policies (
  policy_key,
  name,
  category,
  description,
  enabled,
  config_json,
  version
)
VALUES (
  'free_welcome_grant',
  'Free account welcome coins',
  'credits',
  'One-time coin grant for a newly created free account. This policy never refills monthly.',
  true,
  jsonb_build_object(
    'coinAmount', 50,
    'grantMode', 'once_per_account',
    'expiresAfterDays', null
  ),
  1
)
ON CONFLICT (policy_key) DO NOTHING;

INSERT INTO public.operational_policy_audit_events (
  policy_key,
  policy_version,
  actor_user_id,
  action_type,
  reason,
  before_json,
  after_json
)
SELECT
  policy.policy_key,
  policy.version,
  null,
  'policy_created',
  'Initial migration policy',
  null,
  to_jsonb(policy)
FROM public.operational_policies policy
WHERE policy.policy_key = 'free_welcome_grant'
  AND NOT EXISTS (
    SELECT 1
    FROM public.operational_policy_audit_events audit
    WHERE audit.policy_key = policy.policy_key
  );

-- The recurring allowance column remains part of paid-plan catalog versions,
-- but it is no longer the source of truth for Free. Preserve prior Free values
-- in extensions_json so a rollback does not guess or overwrite catalog data.
UPDATE public.pricing_plan_versions version
SET
  monthly_included_beats = 0,
  extensions_json =
    jsonb_set(
      COALESCE(version.extensions_json, '{}'::jsonb),
      '{preWelcomePolicyMonthlyIncludedBeats}',
      to_jsonb(version.monthly_included_beats),
      true
    )
    || jsonb_build_object('freeCreditPolicyKey', 'free_welcome_grant')
FROM public.pricing_plans plan
WHERE version.plan_id = plan.id
  AND plan.plan_key = 'free'
  AND NOT (COALESCE(version.extensions_json, '{}'::jsonb) ? 'preWelcomePolicyMonthlyIncludedBeats');

CREATE OR REPLACE FUNCTION public.admin_update_operational_policy(
  p_policy_key text,
  p_enabled boolean,
  p_config_json jsonb,
  p_reason text,
  p_actor_user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_before public.operational_policies%ROWTYPE;
  v_after public.operational_policies%ROWTYPE;
  v_coin_amount numeric;
  v_expiry_text text;
BEGIN
  IF char_length(btrim(COALESCE(p_reason, ''))) < 4 THEN
    RAISE EXCEPTION 'A change reason of at least 4 characters is required';
  END IF;

  IF p_config_json IS NULL OR jsonb_typeof(p_config_json) <> 'object' THEN
    RAISE EXCEPTION 'Policy configuration must be a JSON object';
  END IF;

  SELECT *
  INTO v_before
  FROM public.operational_policies
  WHERE policy_key = p_policy_key
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Operational policy % was not found', p_policy_key;
  END IF;

  IF p_policy_key = 'free_welcome_grant' THEN
    IF COALESCE(p_config_json->>'grantMode', '') <> 'once_per_account' THEN
      RAISE EXCEPTION 'Free welcome grant mode must be once_per_account';
    END IF;

    BEGIN
      v_coin_amount := (p_config_json->>'coinAmount')::numeric;
    EXCEPTION WHEN OTHERS THEN
      RAISE EXCEPTION 'Free welcome coin amount must be numeric';
    END;

    IF v_coin_amount IS NULL
      OR v_coin_amount <= 0
      OR v_coin_amount > 10000
      OR scale(v_coin_amount) > 2 THEN
      RAISE EXCEPTION 'Free welcome coin amount must be between 0.01 and 10000 with at most 2 decimal places';
    END IF;

    v_expiry_text := p_config_json->>'expiresAfterDays';
    IF v_expiry_text IS NOT NULL THEN
      IF v_expiry_text !~ '^[0-9]+$'
        OR v_expiry_text::integer < 1
        OR v_expiry_text::integer > 3650 THEN
        RAISE EXCEPTION 'Expiry days must be null or an integer from 1 to 3650';
      END IF;
    END IF;
  END IF;

  UPDATE public.operational_policies
  SET
    enabled = p_enabled,
    config_json = p_config_json,
    version = version + 1,
    updated_at = now(),
    updated_by = p_actor_user_id
  WHERE policy_key = p_policy_key
  RETURNING * INTO v_after;

  INSERT INTO public.operational_policy_audit_events (
    policy_key,
    policy_version,
    actor_user_id,
    action_type,
    reason,
    before_json,
    after_json
  )
  VALUES (
    v_after.policy_key,
    v_after.version,
    p_actor_user_id,
    'policy_updated',
    btrim(p_reason),
    to_jsonb(v_before),
    to_jsonb(v_after)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_update_operational_policy(text, boolean, jsonb, text, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_operational_policy(text, boolean, jsonb, text, uuid)
  TO service_role;

CREATE OR REPLACE FUNCTION public.apply_free_welcome_grant(p_user_id uuid)
RETURNS TABLE (
  grant_id uuid,
  granted boolean,
  beats_granted numeric,
  expires_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_policy public.operational_policies%ROWTYPE;
  v_existing_grant public.beat_grants%ROWTYPE;
  v_grant_id uuid;
  v_beats numeric(12,2);
  v_expires_at timestamptz;
  v_expiry_text text;
BEGIN
  -- Serialize checks for the same account so signup and runtime fallback cannot
  -- race one another into two grants.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  SELECT *
  INTO v_policy
  FROM public.operational_policies
  WHERE policy_key = 'free_welcome_grant';

  IF NOT FOUND OR NOT v_policy.enabled THEN
    RETURN QUERY SELECT null::uuid, false, 0::numeric, null::timestamptz;
    RETURN;
  END IF;

  -- Historical free_allowance rows count as the account's welcome benefit.
  -- This deliberately prevents an extra grant for users who already received
  -- one or more monthly allowances before this policy was tightened.
  SELECT *
  INTO v_existing_grant
  FROM public.beat_grants
  WHERE user_id = p_user_id
    AND source_type = 'free_allowance'
  ORDER BY granted_at ASC, id ASC
  LIMIT 1;

  IF FOUND THEN
    RETURN QUERY
    SELECT v_existing_grant.id, false, 0::numeric, v_existing_grant.expires_at;
    RETURN;
  END IF;

  IF COALESCE(v_policy.config_json->>'grantMode', '') <> 'once_per_account' THEN
    RAISE EXCEPTION 'Unsupported free welcome grant mode';
  END IF;

  v_beats := round(((v_policy.config_json->>'coinAmount')::numeric / 10.0), 2);
  IF v_beats <= 0 THEN
    RAISE EXCEPTION 'Free welcome grant resolves to zero internal beats';
  END IF;

  v_expiry_text := v_policy.config_json->>'expiresAfterDays';
  v_expires_at := CASE
    WHEN v_expiry_text IS NULL THEN null
    ELSE now() + make_interval(days => v_expiry_text::integer)
  END;

  INSERT INTO public.beat_grants (
    user_id,
    source_type,
    source_ref_id,
    currency_code,
    beats_total,
    beats_remaining,
    expires_at,
    metadata_json
  )
  VALUES (
    p_user_id,
    'free_allowance',
    format('policy:free_welcome_grant:v%s:%s', v_policy.version, p_user_id),
    null,
    v_beats,
    v_beats,
    v_expires_at,
    jsonb_build_object(
      'policyKey', v_policy.policy_key,
      'policyVersion', v_policy.version,
      'grantMode', 'once_per_account',
      'coinAmount', (v_policy.config_json->>'coinAmount')::numeric
    )
  )
  RETURNING id INTO v_grant_id;

  RETURN QUERY SELECT v_grant_id, true, v_beats::numeric, v_expires_at;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_free_welcome_grant(uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_free_welcome_grant(uuid)
  TO service_role;

CREATE OR REPLACE FUNCTION public.apply_free_welcome_grant_on_signup()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.apply_free_welcome_grant(NEW.id);
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- A policy or wallet problem must never prevent account creation. The
  -- application runtime invokes the same idempotent function as a safety net.
  RAISE WARNING 'Could not apply free welcome grant for user %: %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_free_welcome_grant_on_signup()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS auth_users_apply_free_welcome_grant ON auth.users;
CREATE TRIGGER auth_users_apply_free_welcome_grant
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.apply_free_welcome_grant_on_signup();
